// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiSEnZS7QZELdkl5Mbxq8ddZQJuOmhtUo',
    appId: '1:1088790244412:web:5529834aa528b4c2dca739',
    messagingSenderId: '1088790244412',
    projectId: 'ytbg-player',
    authDomain: 'ytbg-player.firebaseapp.com',
    databaseURL: 'https://ytbg-player-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ytbg-player.appspot.com',
    measurementId: 'G-6WJYQP03SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFA9pgsFtSJz_RTjvaTRH7_wg7ESgfIs',
    appId: '1:1088790244412:android:cf4da5233c4e8cd0dca739',
    messagingSenderId: '1088790244412',
    projectId: 'ytbg-player',
    databaseURL: 'https://ytbg-player-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ytbg-player.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yRFV8eJvs_aoihfSJGs6latx4EEVRuA',
    appId: '1:1088790244412:ios:ea319f795c77216fdca739',
    messagingSenderId: '1088790244412',
    projectId: 'ytbg-player',
    databaseURL: 'https://ytbg-player-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ytbg-player.appspot.com',
    iosClientId: '1088790244412-mp4qi9s5m29p155rf7c19qrlh37tjgga.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_yRFV8eJvs_aoihfSJGs6latx4EEVRuA',
    appId: '1:1088790244412:ios:ea319f795c77216fdca739',
    messagingSenderId: '1088790244412',
    projectId: 'ytbg-player',
    databaseURL: 'https://ytbg-player-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ytbg-player.appspot.com',
    iosClientId: '1088790244412-mp4qi9s5m29p155rf7c19qrlh37tjgga.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtube',
  );
}
